### ISSUE TITLE
Ngnix / PCRE fails to install "fatal error: string"

### ISSUE THREAD

**Issue by crasiak** [rumpkernel/rumprun-packages#10]
Unable to build nginx w/ PCRE support: `make` in rumprun-packages/pcre fails.

``` bash
vagrant@virtualbox-xen:~/rumprun-packages/pcre$ make
make -C build
make[1]: Entering directory `/home/vagrant/rumprun-packages/pcre/build'
rm -f pcre_chartables.c
ln -s ./pcre_chartables.c.dist pcre_chartables.c
make  all-am
make[2]: Entering directory `/home/vagrant/rumprun-packages/pcre/build'
  CC       libpcre_la-pcre_byte_order.lo
  CC       libpcre_la-pcre_compile.lo
  CC       libpcre_la-pcre_config.lo
  CC       libpcre_la-pcre_dfa_exec.lo
  CC       libpcre_la-pcre_exec.lo
  CC       libpcre_la-pcre_fullinfo.lo
  CC       libpcre_la-pcre_get.lo
  CC       libpcre_la-pcre_globals.lo
  CC       libpcre_la-pcre_jit_compile.lo
  CC       libpcre_la-pcre_maketables.lo
  CC       libpcre_la-pcre_newline.lo
  CC       libpcre_la-pcre_ord2utf8.lo
  CC       libpcre_la-pcre_refcount.lo
  CC       libpcre_la-pcre_string_utils.lo
  CC       libpcre_la-pcre_study.lo
  CC       libpcre_la-pcre_tables.lo
  CC       libpcre_la-pcre_ucd.lo
  CC       libpcre_la-pcre_valid_utf8.lo
  CC       libpcre_la-pcre_version.lo
  CC       libpcre_la-pcre_xclass.lo
  CC       libpcre_la-pcre_chartables.lo
  CCLD     libpcre.la
  CC       libpcreposix_la-pcreposix.lo
  CCLD     libpcreposix.la
  CXX      libpcrecpp_la-pcrecpp.lo
pcrecpp.cc:43:18: fatal error: string: No such file or directory
 #include <string>
                  ^
compilation terminated.
make[2]: *** [libpcrecpp_la-pcrecpp.lo] Error 1
make[2]: Leaving directory `/home/vagrant/rumprun-packages/pcre/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/vagrant/rumprun-packages/pcre/build'
make: *** [build/libpcre.la] Error 2
```

gcc/g++ version 4.8.4-2ubuntu1~14.04

Please let me know of any other information I can provide.

**Comment by kaveman-** [comment]
do you have the c++ bits compiled ?

here's a quick test you can do:

```
$ cat > cpptest.cpp << EOF
#include <string>
#include <iostream>

int main() {
    std::string msg("Hello");
    std::cout << msg << std::endl;
    return 0;
}
EOF

$ x86_64-rumprun-netbsd-g++ -c cpptest.cpp
```

if the compilation errors out, you probably don't have the c++ bits compiled.

**Comment by anttikantee** [comment]
Are you building on 32bit?  pcre build seems to fail for me on x86_32.

**Comment by crasiak** [comment]
Nope. 64bit. But It looks like I don't have the c++ bits compiled.

I've run `build-rr.sh xen` - I didn't see anything else mentioned in the [static website tutorial](https://github.com/rumpkernel/wiki/wiki/Tutorial%3A-Serve-a-static-website-as-a-Unikernel)

what else needs to be compiled?

**Comment by anttikantee** [comment]
You don't need to compile anything else, but a C++ compiler which supports at least std=c++11 is required.

I don't know which compiler Ubuntu 14.04 comes with.  On Travis CI (which uses an old Ubuntu) we install g++-4.8 and use that.  See .travis.yml.

**Comment by crasiak** [comment]
Ok. PCRE is building now.

For posterity: 
I rebuilt rumprun (build-rr.sh) -after reinstalling g++ 4.8. 

In desperation last night I installed libtool, libpcre3, libpcre3-dev, libpcre++-dev, lib64stdc++-4.8-dev not sure if any of those are necessary - but figured I write it down anyway.

Thanks for your help!

**Comment by anttikantee** [comment]
Good to hear.

Yea, you don't need anything on the host, so those installations were unnecessary.  You can imagine compiling for rumprun as compiling for another CPU architecture: anything on the host will not be used (well, except the cross toolchain, of course).

**Comment by crasiak** [comment]
Great. I'll remove those from the system as I don't really need them.

This is totally off topic, but do you know any good resources for rumprun settings? I'm having a hard time setting up networking for this [nginx example](https://github.com/rumpkernel/wiki/wiki/Tutorial%3A-Serve-a-static-website-as-a-Unikernel) on xen - there's no `-n` available in the tool as shown in the tutorial and console output indicates it's looking for `xenbr0` bridge, when the system I'm testing on only has the bridge `br0`... 

(apologies for the crossed thread)

**Comment by anttikantee** [comment]
What -n?  Do you mean -net?

For questions like that, it's better to ask the mailing list (rumpkernel-users@freelists.org).  I think only a handful of people read these github issues.

You can specify the backing interface options after the second comma for the -I argument, but I can't quite remember what you had to put there.  Maybe just the bridge name is enough, but consult the xl docs to be sure.  Use rumprun -D/-T to make sure that the generated config file contains what you wanted.

**Comment by crasiak** [comment]
Oh! Apologies. I realized after looking over the tutorial again I completely misunderstood/misread.

Thanks for all your help and the link to the mailing list. I've subscribed and will be peppering them with questions moving forward. :)

Thanks again for taking the time.
