### ISSUE TITLE
rumprun-packages uses incorrect rump platform path

### ISSUE THREAD

**Issue by neeraj9** [rumpkernel/rumprun-packages#11]
The following in Makefile.inc is incorrect and should infact refer to $(RUMPRUN_APPTOOL_DIR)/../rumprun

RUMPRUN_SYSROOT=$(shell realpath $(RUMPRUN_APPTOOLS_DIR)/../rump)

**Comment by anttikantee** [comment]
Can you send a tested patch as a pull req?

**Comment by neeraj9** [comment]
sure
