### ISSUE TITLE
Python3 example doesn't build on Ubuntu 14.04

### ISSUE THREAD

**Issue by ganglio** [rumpkernel/rumprun-packages#115]
the `make` command quits with the following error:

x86_64-rumprun-netbsd-gcc -DNDEBUG -g  -O3 -Wall -Wstrict-prototypes -static -static-libgcc -L/home/vagrant/rump/rumprun-packages/pkgs/lib  -L/home/vagrant/rump/rumprun-packages/pkgs/lib Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Objects/obmalloc.o Python/dynamic_annotations.o Python/mysnprintf.o Python/pyctype.o Parser/tokenizer_pgen.o Parser/printgrammar.o Parser/parsetok_pgen.o Parser/pgenmain.o -lpthread -lutil -o Parser/pgen
cc: error: Python/dynamic_annotations.o: No such file or directory
cc: error: Python/mysnprintf.o: No such file or directory
cc: error: Python/pyctype.o: No such file or directory
make[1]: **\* [Parser/pgen] Error 1
make[1]: Leaving directory `/home/vagrant/rump/rumprun-packages/python3/build'
make: **\* [build/python] Error 2

**Comment by anttikantee** [comment]
Look earlier in the log to see why the missing objects have not been compiled (Python/dynamic_annotations.o etc.)

**Comment by ganglio** [comment]
Stupid rookie mistake from my side. Using a Vagrant machine with a shared folder over a case insensitive FS on the guest. Everything works splendidly. Thanks for your help.

**Comment by anttikantee** [comment]
There are no stupid rookie mistakes, there are only stupid computers.

Anyway, good that it got fixed without me having to do anything! ;-)
