### ISSUE TITLE
Python 3.5.2 and up support

### ISSUE THREAD

**Issue by pyaltocor** [rumpkernel/rumprun-packages#121]
Any plans in the near future to add support for Python 3.5.2 and up?

**Comment by rday** [comment]
Absolutely! Let me take a look and make sure nothing breaks during the
upgrade.

**Comment by rday** [comment]
Fixed in 09eae5ad55206cc390fdef49c9b163621f54a8cf !

**Comment by anttikantee** [comment]
@rday thanks! Are any patches upstreamable?

**Comment by rday** [comment]
No. Although I haven't really followed up recently. There was a change in
3.5.2 which broke one of my patches. The change was related to additional
cross compilation features in the upstream Makefile. But Python considers a
cross compilation to be building between x86 and x86_64. It didn't look
like the breaking changes indicated something new that would allow
upstreaming the rump package cross compilation changes.

**Comment by pyaltocor** [comment]
Thank you!
