### ISSUE TITLE
zeromq package for rump kernel with two tests. 

### ISSUE THREAD

**Issue by kvart2006** [rumpkernel/rumprun-packages#123]
I would like to add to the package list a new package.

**Comment by kaveman-** [comment]
go ahead and submit a pull request.

**Comment by kvart2006** [comment]
I need a Github login/password apparently.

**Comment by marinbek** [comment]
Closing as @kvart2006 obviously managed to make a pr: https://github.com/rumpkernel/rumprun-packages/pull/127
