### ISSUE TITLE
PCRE not found

### ISSUE THREAD

**Issue by Ulrar** [rumpkernel/rumprun-packages#133]
Hi,

Looks like the PCRE package needs an update :

>Connecting to ftp.csx.cam.ac.uk|131.111.8.115|:21... connected.
>Logging in as anonymous ... Logged in!
>==> SYST ... done.    ==> PWD ... done.
>==> TYPE I ... done.  ==> CWD (1) /pub/software/programming/pcre ... done.
>==> SIZE pcre-8.38.tar.gz ... done.
>
>==> PASV ... done.    ==> RETR pcre-8.38.tar.gz ... 
>No such file ‘pcre-8.38.tar.gz’.

Looking at the FTP it seems like 8.39 is now the lowest version on there.

**Comment by kaveman-** [comment]
I'll update it shortly.

**Comment by yinwoods** [comment]
change UPSTREAM=ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.39.tar.gz in Makefile which in pcre directory solved my problem

**Comment by kaveman-** [comment]
8.40 is available.

**Comment by kaveman-** [comment]
pcre updated to 8.40.
