### ISSUE TITLE
nodejs does not build

### ISSUE THREAD

**Issue by justincormack** [rumpkernel/rumprun-packages#26]
```
make: *** No rule to make target `build/node.gyp', needed by `build/out/Release/node'.  Stop.
```

Is this file missing from checkin or is there a rule missing?

**Comment by anttikantee** [comment]
Dunno, built for me when I tried it, but apparently that dependency was added later.

cc @davedoesdev (or are you getting these notifications otherwise too?)

**Comment by davedoesdev** [comment]
@justincormack could you try a clean build again please with the latest version? Thanks
