### ISSUE TITLE
erlang: clustering example is crash-dumping

### ISSUE THREAD

**Issue by igalic** [rumpkernel/rumprun-packages#30]
when trying to run the clustering example

``` shell
#!/bin/sh

ERLAPP_PATH=/apps/erlang
ERLHOME=/tmp
ERLPATH=/opt/erlang
NAME=sample
IP=10.0.120.101
COOKIE=mycookie

rumprun kvm \
   -I if,vioif,'-net tap,script=no,ifname=tap0' \
   -W if,inet,static,${IP}/24 \
   -e ERL_INETRC=$ERLPATH/erl_inetrc \
   -b images/erlang.iso,$ERLPATH \
   -b examples/app.iso,$ERLAPP_PATH \
   -i beam.hw.bin \
     "-- -root $ERLPATH/lib/erlang -progname erl -- \
      -home $ERLHOME -noshell -pa $ERLAPP_PATH -s erlpmd_ctl start \
      -s setnodename start ${NAME}@${IP},$COOKIE \
      -s echoserver start"
```

erlpmd crashdumps:

``` erlang
{"init terminating in do_boot",{function_clause,
  [{setnodename,start,[['levix@10.0.120.100,mycookie']],
  [{file,"setnodename.erl"},{line,9}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
```

**Comment by igalic** [comment]
okay! progress!
the cluster example crash-dumps on my machine!
```
igalic@levix ~/s/r/r/erlang (master=)> erl -- -home examples/app  -s erlpmd_ctl -start -s setnodename sample@10.0.120.100 mycookie -s echoserver start
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

{"init terminating in do_boot",{undef,[{erlpmd_ctl,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
igalic@levix ~/s/r/r/erlang (master=) [1]> 
```

**Comment by igalic** [comment]
it's weird that it's failing, since it's [`erpmd_ctl`](https://github.com/lemenkov/erlpmd) *is* [patched in](https://github.com/rumpkernel/rumprun-packages/blob/master/erlang/patches/815.patch#L617)

**Comment by anttikantee** [comment]
Same for me (the crash after boot).

I don't recall ever testing the cluster mode, so not sure if the problem was always there (e.g. due to forgetting to commit something), or if the problem was introduced by recent changes.  I guess one could checkout rumprun and packages from around when erlang was introduced, but maybe easier to wait and see if @neeraj9 recognizes the problem.

**Comment by igalic** [comment]
i've now updated the description, after having traced the issue down the rabbit hole far enough ;)
now it's _just_ an issue with the [setnodename.erl](https://github.com/rumpkernel/rumprun-packages/blob/master/erlang/examples/setnodename/setnodename.erl#L9) `start/1` function's

**Comment by igalic** [comment]
aaaaaaaaand it's fixed.

---

updated shell script:

``` shell
#!/bin/sh

ERLAPP_PATH=/apps/erlang
ERLHOME=/tmp
ERLPATH=/opt/erlang
NAME=sample
IP=10.0.120.101
COOKIE=mycookie

rumprun kvm \
   -I if,vioif,'-net tap,script=no,ifname=tap0' \
   -W if,inet,static,${IP}/24 \
   -e ERL_INETRC=$ERLPATH/erl_inetrc \
   -b images/erlang.iso,$ERLPATH \
   -b examples/app.iso,$ERLAPP_PATH \
   -i beam.hw.bin \
     "-- -root $ERLPATH/lib/erlang -progname erl -- \
      -home $ERLHOME -noshell -pa $ERLAPP_PATH -s erlpmd_ctl start \
      -s setnodename start ${NAME}@${IP} $COOKIE \
      -s echoserver start"
```

**Comment by anttikantee** [comment]
Can you give a one-line summary of the problem and fix, so that anyone who runs into this (years) later will immediately have a clue as to what was going on?

Then please submit a pull req.

**Comment by anttikantee** [comment]
patch merged

**Comment by igalic** [comment]
automation > documentation :P
