### ISSUE TITLE
Erlang does not build

### ISSUE THREAD

**Issue by mato** [rumpkernel/rumprun-packages#36]
From https://hub.docker.com/r/mato/rumprun-packages-hw-x86_64/builds/bxvripotmjguzr57khciqgb/:
(apologies for mangled text, cut and paste doesn't work from the log)

```
CC obj/x86_64-rumprun-netbsd/opt/smp/inet_drv.o 
[91mdrivers/common/inet_drv.c: In function 'sctp_set_opts': 
[0m 
[91mdrivers/common/inet_drv.c:6574:26: error: field 'av' has incomplete type struct sctp_assoc_value av; /* Not in SOLARIS10 */ ^ 
[0m 
[91mdrivers/common/inet_drv.c: In function 'sctp_fill_opts': 
[0m 
[91mdrivers/common/inet_drv.c:8027:30: error: storage size of 'av' isn't known struct sctp_assoc_value av; ^ 
[0m 
[91mdrivers/common/inet_drv.c:8042:97: warning: left-hand operand of comma expression has no effect [-Wunused-value] i = LOAD_ASSOC_ID (spec, i, av.assoc_id); ^ 
[0m 
[91mdrivers/common/inet_drv.c:8043:99: warning: left-hand operand of comma expression has no effect [-Wunused-value] i = LOAD_INT (spec, i, av.assoc_value); ^ 
[0m 
[91mdrivers/common/inet_drv.c:8027:30: warning: unused variable 'av' [-Wunused-variable] struct sctp_assoc_value av; ^ 
[0m x86_64-rumprun-netbsd/Makefile:699: recipe for target 'obj/x86_64-rumprun-netbsd/opt/smp/inet_drv.o' failed make[4]: Leaving directory '/build/rumprun-packages/erlang/build/erts/emulator' 
[91mmake[4]: *** [obj/x86_64-rumprun-netbsd/opt/smp/inet_drv.o] Error 1 
[0m /build/rumprun-packages/erlang/build/make/run_make.mk:35: recipe for target 'opt' failed 
[91mmake[3]: *** [opt] Error 2 
[0m make[3]: Leaving directory '/build/rumprun-packages/erlang/build/erts/emulator' Makefile:61: recipe for target 'smp' failed 
[91mmake[2]: *** [smp] Error 2
```

**Comment by mato** [comment]
Note that this is independent of the "Erlang does not build with -j>1" discussed on IRC yesterday, this build is with -j1.

**Comment by anttikantee** [comment]
This looks like a problem introduced by the recent src-netbsd pull, with sctp now being available.

I have no idea what `sctp_assoc_value` is, and therefore if it's a NetBSD sctp implementation problem or an Erlang upstream problem.

**Comment by igalic** [comment]
no idea what, exactly fixed it, but it's building again.

**Comment by mato** [comment]
Does not build for me with the latest x86_64 rumprun master, with or without using the Docker images for the build. When you say "it's building again", what exactly do you mean?

Note that I've intentionally disabled erlang in the Docker Hub autobuilds for packages, as otherwise they would keep failing until this is fixed.

**Comment by igalic** [comment]
i just reran the build locally in my machine, with the latest rumprun, and rumprun-packages, abs it worked. i'll dig a little deeper to find out what exactly is working.

**Comment by mato** [comment]
On Tuesday, 08.12.2015 at 00:04, Igor Galiæ wrote:

> i just reran the build locally in my machine, with the latest rumprun, and rumprun-packages, abs it worked. i'll dig a little deeper to find out what exactly is working.

Thanks!

**Comment by igalic** [comment]
sadly, all i have to say is: works on my machine™
![rumprun-erlang-build-works](https://cloud.githubusercontent.com/assets/497249/11654368/5e10c7f4-9da5-11e5-8937-528a2f9a585d.png)

**Comment by mato** [comment]
On Tuesday, 08.12.2015 at 03:15, Igor Galić wrote:

> sadly, all i have to say is: works on my machine™
> ![rumprun-erlang-build-works](https://cloud.githubusercontent.com/assets/497249/11654368/5e10c7f4-9da5-11e5-8937-528a2f9a585d.png)

Okay, is there anything special about your machine? What host OS are you
building on? 

Also, just to be 100% sure we're using the same commits, what is the output
of `git rev-list HEAD -1)` for `rumprun`, `rumprun/src-netbsd` and
`rumprun-packages` which you use for the build?

**Comment by igalic** [comment]
```
igalic@levix ~/s/r/r/erlang (master=)> git rev-list HEAD -1
872375a55292fe346d24333878f99bb1c272b7e0
igalic@levix ~/s/r/r/erlang (master=)> ../../rumprun
igalic@levix ~/s/r/rumprun (master=)> git rev-list HEAD -1
458ef5868f5efdc69693b1b29cfdda974027772d
igalic@levix ~/s/r/rumprun (master=)> cd src-netbsd/
igalic@levix ~/s/r/r/src-netbsd ((d16ef24...))> git rev-list HEAD -1
d16ef24b229587c4b7abdafd7f7fe992af1c8039
igalic@levix ~/s/r/r/src-netbsd ((d16ef24...))>
```

```
igalic@levix ~> lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Model name:            Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Stepping:              9
CPU MHz:               1242.382
CPU max MHz:           3100,0000
CPU min MHz:           1200,0000
BogoMIPS:              4988.91
Virtualisation:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0-3
igalic@levix ~> uname -a
Linux levix 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
igalic@levix ~> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
igalic@levix ~> gcc --version
gcc-5.real (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

igalic@levix ~> 
```

**Comment by anttikantee** [comment]
See if you have `HAVE_SCTP_H` defined in `erts/*-rumprun-*/config.h`.  If not, figure out why not.  You should have `netinet/sctp.h` under your rumprun installation directory's `rumprun-*/include`

At any rate, the package should use the same patch as pkgsrc:
http://cvsweb.netbsd.org/bsdweb.cgi/~checkout~/pkgsrc/lang/erlang/patches/patch-erts_emulator_drivers_common_inet__drv.c?rev=1.1&content-type=text/plain

**Comment by igalic** [comment]
`netinet/sctp.h` exists, but `HAVE_SCTP_H` is not set, although it's not clear why, since none of the `configure`s leave a `config.log`

**Comment by igalic** [comment]
works with the patch. see #52

**Comment by mato** [comment]
Confirmed, works for me with #52. Merged. Thanks all for the investigation!

**Comment by anttikantee** [comment]
I'd rather leave this open until @igalic figures out why `HAVE_SCTP_H` is not set for him, better not leave any masked bugs hanging around -- especially since during the weekend someone was complaining about the nginx build not finding libpcre.

It should be easy enough to just run the configure test by hand, apply `-v`, and figure it out from there.

**Comment by anttikantee** [comment]
btw, @igalic, do you want to be the erlang package maintainer?  @neeraj9 seems to have gone missing.

**Comment by igalic** [comment]
so, apparently, when you look hard enough at the issue, it'll fail.

colour me confused.

**Comment by neeraj9** [comment]
I've been awfully busy with some project... Not missing :)
I can maintain the Erlang package though these couple of weeks would be tough to make any contribution.
-Neeraj
On Dec 8, 2015 9:16 PM, Antti Kantee <notifications@github.com> wrote:btw, @igalic, do you want to be the erlang package maintainer?  @neeraj9 seems to have gone missing.

**Comment by neeraj9** [comment]
Huh! I've been out of action for a while and couldn't keep up with the recent changes. Will try to allocate some cycles this week if its not fixed already.
What's the error?
-Neeraj
On Dec 8, 2015 9:53 PM, Igor Galić <notifications@github.com> wrote:so, apparently, when you look hard enough at the issue, it'll fail.

colour me confused.

**Comment by neeraj9** [comment]
fwiw if sctp isn't a must have (which has limited use in general in www) then better to disable it via changing the Makefile and specify --disable-sctp in ERLANG_CONF_OPTS.

Ideally SCTP_DELAYED_ACK_TIME or HAVE_DECL_SCTP_DELAYED_ACK_TIME should never have been defined in the first place in netbsd when not supported. The erts/configure specifically checks for the symbol in netinet/sctp.h. I am surprised why SCTP_DELAYED_ACK_TIME is defined there at all (for netbsd), when unsupported.

**Comment by neeraj9** [comment]
huh! netbsd netinet/sctp.h does have SCTP_DELAYED_ACK_TIME defined, which misses the sctp_assoc_value structure/support. Go figure!!

ref: http://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/sys/netinet/sctp.h

**Comment by neeraj9** [comment]
closing this since there is a patch for working around this long back.
