### ISSUE TITLE
changing mysql native ssl type to native

### ISSUE THREAD

**Issue by yuval-k** [rumpkernel/rumprun-packages#78]
when building the mysql package, a mysql native is built to bootstrap the data folder.
this mysql is built with (in the Makefile's build/mysql_native_stamp target ):

```
-DWITH_SSL=system
```

which introduces an extra dependency. this is not needed as this sql binary is only used for bootstrapping and not and the resulting image.

I suggest changing it to

```
-DWITH_SSL=bundled
```

to use the ssl version bundled in mysql and avoid the dependancy.

**Comment by anttikantee** [comment]
Is this fixed now?

**Comment by yuval-k** [comment]
fixed by commit:
468fedca29914902ffd6de1e2c4659dadf6b9853
