### ISSUE TITLE
OpenJDK support

### ISSUE THREAD

**Issue by saturnism** [rumpkernel/rumprun-packages#99]
It'd be nice to be able to run Java :)

**Comment by reuben-sutton** [comment]
I tried this before, OpenJDK seems to lack a static compilation target and adding one would be non-trivial.

I think JamVM does, but I'm not sure about it's completeness or performance vs HotSpot.

**Comment by VincentS** [comment]
OSv from Cloudius Software supports Java out of the box.

**Comment by anttikantee** [comment]
openjdk8 is available now
